// This file is generated by Style Dictionary
export type DesignToken = string;

export interface DesignTokens {
  [key: string]: DesignTokens | DesignToken;
}

declare const tokens: {
  brand: {
    accent: {
      option1: DesignToken;
      option2: DesignToken;
      option3: DesignToken;
      option4: DesignToken;
    };
    business: DesignToken;
    official: DesignToken;
    onContrasted: DesignToken;
    primary: DesignToken;
    secondary: DesignToken;
    gradient: {
      blueGreen: DesignToken;
      greenYellow: DesignToken;
      pinkRed: DesignToken;
      pinkViolet: DesignToken;
      violetBlue: DesignToken;
      violetRed: DesignToken;
      yellowOrange: DesignToken;
    };
  };
  content: {
    data: {
      first: DesignToken;
      fourth: DesignToken;
      second: DesignToken;
      third: DesignToken;
    };
    highlight: {
      firstLevel: {
        background: DesignToken;
        main: DesignToken;
      };
      fourthLevel: {
        background: DesignToken;
        main: DesignToken;
      };
      secondLevel: {
        background: DesignToken;
        main: DesignToken;
      };
      thirdLevel: {
        background: DesignToken;
        main: DesignToken;
      };
    };
  };
  creativeAssets: {
    detail: DesignToken;
    thumbnail: DesignToken;
  };
  social: {
    apple: DesignToken;
    facebook: DesignToken;
    google: DesignToken;
    linkedin: DesignToken;
    hover: DesignToken;
  };
  chip: {
    disclose: {
      background: {
        enabled: DesignToken;
        error: DesignToken;
      };
      border: {
        enabled: DesignToken;
        error: DesignToken;
      };
      input: DesignToken;
    };
  };
  icon: {
    disclosureIndicator: DesignToken;
    error: DesignToken;
    onContrastedHighlighted: DesignToken;
    disabled: DesignToken;
    minor: DesignToken;
    onContrasted: DesignToken;
    onMain: DesignToken;
    onMainHighlighted: DesignToken;
  };
  interaction: {
    danger: DesignToken;
    disabled: DesignToken;
    filter: DesignToken;
    floatingMenu: DesignToken;
    hover: DesignToken;
    navigationEnabled: DesignToken;
    onContrasted: {
      disabled: DesignToken;
      enabled: DesignToken;
      hover: DesignToken;
      navigationEnabled: DesignToken;
      onEnabled: DesignToken;
      onHover: DesignToken;
      onSelected: DesignToken;
      selected: DesignToken;
    };
    onEnabled: DesignToken;
    onHover: DesignToken;
    onSelected: DesignToken;
    enabled: DesignToken;
    selected: DesignToken;
    border: DesignToken;
  };
  layout: {
    surface: {
      tooltip: DesignToken;
      alternativeBackground: DesignToken;
      background: DesignToken;
      border: DesignToken;
    };
    background: {
      video: DesignToken;
      alternative: DesignToken;
      dashboard: DesignToken;
      main: DesignToken;
      navigation: DesignToken;
      navigationAlternative: DesignToken;
      overlay: DesignToken;
      funnel: DesignToken;
    };
    line: {
      divider: DesignToken;
      outline: DesignToken;
      title: DesignToken;
    };
  };
  menu: {
    background: {
      selectedEnabled: DesignToken;
      selectedHover: DesignToken;
      unselectedEnabled: DesignToken;
      unselectedHover: DesignToken;
    };
  };
  notification: {
    danger: {
      background: DesignToken;
      main: DesignToken;
    };
    error: {
      background: DesignToken;
      main: DesignToken;
    };
    info: {
      background: DesignToken;
      main: DesignToken;
    };
    neutral: {
      background: DesignToken;
      main: DesignToken;
    };
    valid: {
      background: DesignToken;
      main: DesignToken;
    };
    warning: {
      background: DesignToken;
      main: DesignToken;
    };
  };
  sort: {
    disabled: DesignToken;
    enabled: DesignToken;
    selected: DesignToken;
  };
  form: {
    field: {
      background: {
        disabled: DesignToken;
        enabled: DesignToken;
        error: {
          enabled: DesignToken;
          hover: DesignToken;
        };
        locked: DesignToken;
        activeDrop: DesignToken;
      };
      border: {
        disabled: DesignToken;
        enabled: DesignToken;
        error: {
          enabled: DesignToken;
          hover: DesignToken;
        };
        focus: DesignToken;
        hover: DesignToken;
        locked: DesignToken;
      };
      input: DesignToken;
      placeholder: DesignToken;
    };
    label: {
      disabled: DesignToken;
      empty: DesignToken;
      error: DesignToken;
      filled: DesignToken;
      focus: DesignToken;
      helper: DesignToken;
      locked: DesignToken;
    };
    selection: {
      icon: {
        disabled: DesignToken;
        enabled: DesignToken;
        error: DesignToken;
        minor: DesignToken;
        selected: DesignToken;
      };
      text: {
        disabled: DesignToken;
        enabled: DesignToken;
      };
    };
  };
  skeleton: {
    badge: DesignToken;
    image: DesignToken;
    text: DesignToken;
  };
  text: {
    onContrasted: DesignToken;
    onMain: DesignToken;
    onMainDisabled: DesignToken;
    onMainMinor: DesignToken;
    onMainSecondary: DesignToken;
    onTooltip: DesignToken;
  };
  analytics: {
    first: DesignToken;
    second: DesignToken;
    third: DesignToken;
  };
  progress: {
    completion: {
      active: DesignToken;
      disabledActive: DesignToken;
      disabledEnabled: DesignToken;
      disabledExpected: DesignToken;
      enabled: DesignToken;
      expected: DesignToken;
    };
    event: {
      awaitingFeedback: DesignToken;
      canceled: DesignToken;
      completed: DesignToken;
      noShow: DesignToken;
      ongoing: DesignToken;
      scheduled: DesignToken;
    };
    learningAsset: {
      background: {
        acquired: DesignToken;
        main: DesignToken;
        passed: DesignToken;
      };
      awaiting: DesignToken;
      failed: DesignToken;
      inProgress: DesignToken;
      locked: DesignToken;
      notStarted: DesignToken;
      onPassed: DesignToken;
      passed: DesignToken;
      readyToPresent: DesignToken;
      retry: DesignToken;
    };
  };
  videocall: {
    active: {
      border: DesignToken;
      enabled: DesignToken;
      hover: DesignToken;
      icon: DesignToken;
    };
    danger: {
      enabled: DesignToken;
      hover: DesignToken;
    };
    default: {
      border: DesignToken;
      enabled: DesignToken;
      hover: DesignToken;
      icon: DesignToken;
    };
    warning: {
      border: DesignToken;
      enabled: DesignToken;
      hover: DesignToken;
      icon: DesignToken;
    };
  };
  topic: {
    business: {
      background: DesignToken;
      detail: DesignToken;
      primary: DesignToken;
      thumbnail: DesignToken;
    };
    career: {
      background: DesignToken;
      detail: DesignToken;
      primary: DesignToken;
      thumbnail: DesignToken;
    };
    cybersecurity: {
      background: DesignToken;
      detail: DesignToken;
      primary: DesignToken;
      thumbnail: DesignToken;
    };
    data: {
      background: DesignToken;
      detail: DesignToken;
      primary: DesignToken;
      thumbnail: DesignToken;
    };
    design: {
      background: DesignToken;
      detail: DesignToken;
      primary: DesignToken;
      thumbnail: DesignToken;
    };
    development: {
      background: DesignToken;
      detail: DesignToken;
      primary: DesignToken;
      thumbnail: DesignToken;
    };
    hr: {
      background: DesignToken;
      detail: DesignToken;
      primary: DesignToken;
      thumbnail: DesignToken;
    };
    marketingComs: {
      background: DesignToken;
      detail: DesignToken;
      primary: DesignToken;
      thumbnail: DesignToken;
    };
    other: {
      background: DesignToken;
      detail: DesignToken;
      primary: DesignToken;
      thumbnail: DesignToken;
    };
    pedagogy: {
      background: DesignToken;
      detail: DesignToken;
      primary: DesignToken;
      thumbnail: DesignToken;
    };
    pm: {
      background: DesignToken;
      detail: DesignToken;
      primary: DesignToken;
      thumbnail: DesignToken;
    };
    productivitySoftwares: {
      background: DesignToken;
      detail: DesignToken;
      primary: DesignToken;
      thumbnail: DesignToken;
    };
    si: {
      background: DesignToken;
      detail: DesignToken;
      primary: DesignToken;
      thumbnail: DesignToken;
    };
    softSkills: {
      background: DesignToken;
      detail: DesignToken;
      primary: DesignToken;
      thumbnail: DesignToken;
    };
    supplyChain: {
      background: DesignToken;
      detail: DesignToken;
      primary: DesignToken;
      thumbnail: DesignToken;
    };
  };
};

export default tokens;
