// This file is generated by Style Dictionary
export type DesignToken = string;

export interface DesignTokens {
  [key: string]: DesignTokens | DesignToken;
}

declare const tokens: {
  black: DesignToken;
  emperor: DesignToken;
  dimGrey: DesignToken;
  alto: DesignToken;
  gainsboro: DesignToken;
  galleryGrey: DesignToken;
  whisper: DesignToken;
  wildSand: DesignToken;
  whiteSmoke: DesignToken;
  greyFifty: DesignToken;
  white: DesignToken;
  fire: DesignToken;
  guardsmanRed: DesignToken;
  pomegranate: DesignToken;
  royalPurple: DesignToken;
  orange: DesignToken;
  macaronyAndCheese: DesignToken;
  blueStone: DesignToken;
  blueLagoon: DesignToken;
  spray: DesignToken;
  congressBlue: DesignToken;
  lochmara: DesignToken;
  anakiwa: DesignToken;
  cobalt: DesignToken;
  blueRibbon: DesignToken;
  pattendsBlue: DesignToken;
  prussianBlue: DesignToken;
  regalBlue: DesignToken;
  burnham: DesignToken;
  aquaDeep: DesignToken;
  aquaIsland: DesignToken;
  crusoe: DesignToken;
  seaGreen: DesignToken;
  grannyAppleSmith: DesignToken;
  teal: DesignToken;
  navyBlue: DesignToken;
  darkBlue: DesignToken;
  daisyBush: DesignToken;
  mauve: DesignToken;
  mediumPurple: DesignToken;
  seance: DesignToken;
  amethyst: DesignToken;
  pinkLace: DesignToken;
  paprika: DesignToken;
  amaranth: DesignToken;
  sangria: DesignToken;
  mojo: DesignToken;
  romantic: DesignToken;
  springGreen: DesignToken;
  midnightBlue: DesignToken;
  brightBlue: DesignToken;
  pink: DesignToken;
  cpfBlue: DesignToken;
  ironstone: DesignToken;
  portica: DesignToken;
};

export default tokens;
