// This file is generated by Style Dictionary
export type DesignToken = string;

export interface DesignTokens {
  [key: string]: DesignTokens | DesignToken;
}

declare const tokens: {
  contentImpactMobile: {
    highlight: {
      fontFamily: DesignToken;
      fontSize: DesignToken;
      letterSpacing: DesignToken;
      lineHeight: DesignToken;
      fontWeight: DesignToken;
    };
    medium: {
      fontFamily: DesignToken;
      fontSize: DesignToken;
      letterSpacing: DesignToken;
      lineHeight: DesignToken;
      fontWeight: DesignToken;
    };
  };
  contentImpact: {
    highlight: {
      fontFamily: DesignToken;
      fontSize: DesignToken;
      letterSpacing: DesignToken;
      lineHeight: DesignToken;
      fontWeight: DesignToken;
    };
    medium: {
      fontFamily: DesignToken;
      fontSize: DesignToken;
      letterSpacing: DesignToken;
      lineHeight: DesignToken;
      fontWeight: DesignToken;
    };
  };
  content: {
    body: {
      fontFamily: DesignToken;
      fontSize: DesignToken;
      letterSpacing: DesignToken;
      lineHeight: DesignToken;
      fontWeight: DesignToken;
    };
    bodySmall: {
      fontFamily: DesignToken;
      fontSize: DesignToken;
      letterSpacing: DesignToken;
      lineHeight: DesignToken;
      fontWeight: DesignToken;
    };
    caption: {
      fontFamily: DesignToken;
      fontSize: DesignToken;
      letterSpacing: DesignToken;
      lineHeight: DesignToken;
      fontWeight: DesignToken;
    };
    overline: {
      fontFamily: DesignToken;
      fontSize: DesignToken;
      letterSpacing: DesignToken;
      lineHeight: DesignToken;
      fontWeight: DesignToken;
      textTransform: DesignToken;
    };
    subheading: {
      fontFamily: DesignToken;
      fontSize: DesignToken;
      letterSpacing: DesignToken;
      lineHeight: DesignToken;
      fontWeight: DesignToken;
    };
    subheadingSmall: {
      fontFamily: DesignToken;
      fontSize: DesignToken;
      letterSpacing: DesignToken;
      lineHeight: DesignToken;
      fontWeight: DesignToken;
    };
  };
  action: {
    button: {
      fontFamily: DesignToken;
      fontSize: DesignToken;
      letterSpacing: DesignToken;
      lineHeight: DesignToken;
      fontWeight: DesignToken;
    };
    hyperlink: {
      fontFamily: DesignToken;
      fontSize: DesignToken;
      letterSpacing: DesignToken;
      lineHeight: DesignToken;
      fontWeight: DesignToken;
      textDecoration: DesignToken;
    };
    hyperlinkSmall: {
      fontFamily: DesignToken;
      fontSize: DesignToken;
      letterSpacing: DesignToken;
      lineHeight: DesignToken;
      fontWeight: DesignToken;
      textDecoration: DesignToken;
    };
    hyperlinkLarge: {
      fontFamily: DesignToken;
      fontSize: DesignToken;
      letterSpacing: DesignToken;
      lineHeight: DesignToken;
      fontWeight: DesignToken;
    };
  };
  form: {
    checkbox: {
      fontFamily: DesignToken;
      fontSize: DesignToken;
      letterSpacing: DesignToken;
      lineHeight: DesignToken;
      fontWeight: DesignToken;
    };
    chip: {
      fontFamily: DesignToken;
      fontSize: DesignToken;
      letterSpacing: DesignToken;
      lineHeight: DesignToken;
      fontWeight: DesignToken;
    };
    errorMessage: {
      fontFamily: DesignToken;
      fontSize: DesignToken;
      letterSpacing: DesignToken;
      lineHeight: DesignToken;
      fontWeight: DesignToken;
    };
    helper: {
      fontFamily: DesignToken;
      fontSize: DesignToken;
      letterSpacing: DesignToken;
      lineHeight: DesignToken;
      fontWeight: DesignToken;
    };
    input: {
      fontFamily: DesignToken;
      fontSize: DesignToken;
      letterSpacing: DesignToken;
      lineHeight: DesignToken;
      fontWeight: DesignToken;
    };
    label: {
      fontFamily: DesignToken;
      fontSize: DesignToken;
      letterSpacing: DesignToken;
      lineHeight: DesignToken;
      fontWeight: DesignToken;
    };
    radioButton: {
      fontFamily: DesignToken;
      fontSize: DesignToken;
      letterSpacing: DesignToken;
      lineHeight: DesignToken;
      fontWeight: DesignToken;
    };
    checkboxSingle: {
      fontFamily: DesignToken;
      fontSize: DesignToken;
      letterSpacing: DesignToken;
      lineHeight: DesignToken;
      fontWeight: DesignToken;
    };
  };
  titleMobile: {
    h1: {
      fontFamily: DesignToken;
      fontSize: DesignToken;
      letterSpacing: DesignToken;
      lineHeight: DesignToken;
      fontWeight: DesignToken;
    };
    h1Impact: {
      fontFamily: DesignToken;
      fontSize: DesignToken;
      letterSpacing: DesignToken;
      lineHeight: DesignToken;
      fontWeight: DesignToken;
    };
    h2: {
      fontFamily: DesignToken;
      fontSize: DesignToken;
      letterSpacing: DesignToken;
      lineHeight: DesignToken;
      fontWeight: DesignToken;
    };
    h3: {
      fontFamily: DesignToken;
      fontSize: DesignToken;
      letterSpacing: DesignToken;
      lineHeight: DesignToken;
      fontWeight: DesignToken;
    };
    h4: {
      fontFamily: DesignToken;
      fontSize: DesignToken;
      letterSpacing: DesignToken;
      lineHeight: DesignToken;
      fontWeight: DesignToken;
    };
    h5: {
      fontFamily: DesignToken;
      fontSize: DesignToken;
      letterSpacing: DesignToken;
      lineHeight: DesignToken;
      fontWeight: DesignToken;
    };
    h6: {
      fontFamily: DesignToken;
      fontSize: DesignToken;
      letterSpacing: DesignToken;
      lineHeight: DesignToken;
      fontWeight: DesignToken;
    };
  };
  title: {
    h1: {
      fontFamily: DesignToken;
      fontSize: DesignToken;
      letterSpacing: DesignToken;
      lineHeight: DesignToken;
      fontWeight: DesignToken;
    };
    h1Impact: {
      fontFamily: DesignToken;
      fontSize: DesignToken;
      letterSpacing: DesignToken;
      lineHeight: DesignToken;
      fontWeight: DesignToken;
    };
    h2: {
      fontFamily: DesignToken;
      fontSize: DesignToken;
      letterSpacing: DesignToken;
      lineHeight: DesignToken;
      fontWeight: DesignToken;
    };
    h3: {
      fontFamily: DesignToken;
      fontSize: DesignToken;
      letterSpacing: DesignToken;
      lineHeight: DesignToken;
      fontWeight: DesignToken;
    };
    h4: {
      fontFamily: DesignToken;
      fontSize: DesignToken;
      letterSpacing: DesignToken;
      lineHeight: DesignToken;
      fontWeight: DesignToken;
    };
    h5: {
      fontFamily: DesignToken;
      fontSize: DesignToken;
      letterSpacing: DesignToken;
      lineHeight: DesignToken;
      fontWeight: DesignToken;
    };
    h6: {
      fontFamily: DesignToken;
      fontSize: DesignToken;
      letterSpacing: DesignToken;
      lineHeight: DesignToken;
      fontWeight: DesignToken;
    };
  };
};

export default tokens;
